#!/usr/bin/env php
<?php

use AgeekDev\VaporIgnore\Application;
use AgeekDev\VaporIgnore\Commands;
use Illuminate\Container\Container;

/**
 * Require the autoloader.
 */
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

/**
 * Create the container instance.
 */
Container::setInstance($container = new Container);

/**
 * Start the console application.
 */
$app = new Application('Vapor Ignore', '1.0.0');

$app->add(new Commands\CleanIgnoredFilesCommand);
$app->add(new Commands\InitCommand);
$app->add(new Commands\SyncCommand);

$app->run();
