name: Run tests
on:
    push:
        paths:
            - "**.php"
            - "phpunit.xml"
            - "composer.json"
            - "composer.lock"

jobs:
    pest:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  tools: composer:v2
                  coverage: none

            - name: Install composer dependencies
              uses: nick-fields/retry@v2
              with:
                  timeout_minutes: 3
                  max_attempts: 5
                  command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

            - name: Run pest
              timeout-minutes: 2
              run: ./vendor/bin/pest
